# Generated by Django 3.2 on 2021-04-27 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(help_text='正方形の画像にしてください', upload_to='author_icon/', verbose_name='アイコン')),
                ('name', models.CharField(max_length=15, verbose_name='ニックネーム')),
                ('description', models.TextField(max_length=500, verbose_name='自己紹介')),
                ('HomePage', models.CharField(blank=True, max_length=100)),
                ('GitID', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': '記者',
                'verbose_name_plural': '記者リスト',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='カテゴリー名')),
                ('slug', models.SlugField(unique=True, verbose_name='英語名')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='category_thumbnail/', verbose_name='イメージ画像')),
            ],
            options={
                'verbose_name': 'カテゴリー',
                'verbose_name_plural': 'カテゴリーリスト',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='役職名')),
                ('slug', models.SlugField(unique=True, verbose_name='英語名')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '役職',
                'verbose_name_plural': '役職リスト',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='タグ名')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='英語名')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグリスト',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='images/', verbose_name='サムネ')),
                ('title', models.CharField(max_length=75, verbose_name='タイトル')),
                ('content', models.CharField(max_length=5000, verbose_name='本文')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.author')),
            ],
            options={
                'verbose_name': 'ニュース',
                'verbose_name_plural': 'ニュース投稿',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='blog_thumbnail/', verbose_name='サムネ')),
                ('title', models.CharField(max_length=75, verbose_name='タイトル')),
                ('description', models.CharField(max_length=255, verbose_name='headタグでの説明')),
                ('content', models.CharField(max_length=5000, verbose_name='本文')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(null=True, verbose_name='公開日')),
                ('is_public', models.BooleanField(default=False, verbose_name='公開する')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.category')),
                ('tags', models.ManyToManyField(blank=True, to='api.Tag')),
            ],
            options={
                'verbose_name': '記事',
                'verbose_name_plural': 'ブログ投稿',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='author',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.role'),
        ),
    ]
